[[https://travis-ci.org/CodeFalling/hexo-renderer-org][https://travis-ci.org/CodeFalling/hexo-renderer-org.svg]]
[[https://www.npmjs.com/package/hexo-renderer-org][https://badge.fury.io/js/hexo-renderer-org.svg]]

* Table of Contents                                               :TOC_4_org:
  - [[hexo-renderer-org][hexo-renderer-org]]
  - [[Usage][Usage]]
 - [[Options][Options]]
 - [[How to create new post][How to create new post]]
 - [[Q&A][Q&A]]
   - [[How to add ~Read more~ button?][How to add ~Read more~ button?]]
   - [[How to set caption of image?][How to set caption of image?]]
   - [[Old pure-js version][Old pure-js version]]
   - [[Front-matter not work?][Front-matter not work?]]
   - [[How to enable line number?][How to enable line number?]]

*  hexo-renderer-org

Hexo renderer plugin for emacs org-mode

中文动态：[[http://codefalling.com/tags/hexo-renderer-org/][标签: hexo-renderer-org | M-x codefalling]]

*  Usage

Cd to your hexo blog.Run

#+BEGIN_SRC shell
npm install https://github.com/CodeFalling/hexo-renderer-org#emacs --save
#+END_SRC

You can also install it from npm,too.

Then restart your hexo server.

* Options

You can configure this plugin in ~_config.yml~.

#+BEGIN_SRC yml
org:
  emacs: '/Applications/Emacs.app/Contents/MacOS/Emacs'
  common: '#+OPTIONS: toc:nil'
  cachedir: './hexo-org-cache/'
#+END_SRC

1. ~emacs~ is execute file of emacs
2. ~common~ is common org content or you want to insert before renderer every org file.This is a example to disable toc.
3. ~cachedir~ is where your cache file located.With this option ~hexo-org-renderer~ will enable cache. *Recommend for a much faster speed*.
   Default enable.
* How to create new post

Create ~balbala.org~ in source/_posts/,there is a template:

#+BEGIN_SRC org
  ,#+TITLE: Hello,orgmode
  ,#+DATE: <2015-11-15 Sun 17:00>
  ,#+TAGS: emacs, orgmode, hexo
  ,#+LAYOUT: post
  ,#+CATEGORIES: orgmode
  ,* Orgmode
  ,** Why org
  ,#+BEGIN_SRC js
  console.log('hello');
  ,#+END_SRC
  我编不下去了。。
#+END_SRC

* Q&A

** How to add ~Read more~ button?

Place

#+BEGIN_SRC org
  ,#+BEGIN_HTML
  <!--more-->
  ,#+END_SRC
#+END_SRC

in where you would like to add a ~Read more~

** How to set caption of image?
Hexo use `alt` as title of image.

So just use
#+BEGIN_EXAMPLE
  #+ATTR_HTML:  :alt caption
  [[image url]]
#+END_EXAMPLE
** Old pure-js version

See [[https://github.com/CodeFalling/hexo-renderer-org/tree/old-js-version][CodeFalling/hexo-renderer-org at old-js-version]] for old pure-js version.

** Front-matter not work?

Orgmode has its own way to describe meta info of post,such as title,date etc.

| Front-matter | Orgmode      | Value                                                             |
|--------------+--------------+-------------------------------------------------------------------|
| layout       | #+LAYOUT     | post/page                                                         |
| title        | #+TITLE      | string                                                            |
| date         | #+DATE       | <2015-11-16 Mon 20:45>, you can use ~M-x org-time-stamp~ in emacs |
| comments     | #+COMMENTS   | yes/no                                                            |
| tags         | #+TAGS       | tag1, tag2, tag3                                                  |
| categories   | #+CATEGORIES |                                                                   |

** How to enable line number?
Config in your ~_config.yml~

#+BEGIN_EXAMPLE
  highlight:
    enable: true
    number: false
#+END_EXAMPLE
