#+TITLE: hexo-renderer-org (fork)

[[https://circleci.com/gh/coldnew/hexo-renderer-org][https://circleci.com/gh/coldnew/hexo-renderer-org.svg?style=svg]]

[[https://hexo.io][Hexo]] renderer plugin for emacs [[https://orgmode.org/][org-mode]].

[[https://coldnew.github.io/hexo-org-example/2017/03/05/getting-started-with-hexo-and-org-mode/][Getting Started Guide]]

* Table of Contents                                               :TOC_2_gh:
 - [[#why-fork-][Why fork ?]]
 - [[#difference-with-original-one][Difference with original one]]
 - [[#installation][Installation]]
 - [[#options][Options]]
 - [[#create-post][Create Post]]
 - [[#front-matters][Front-matters]]
 - [[#tutorials][Tutorials]]
 - [[#q--a][Q & A]]
   - [[#how-to-add-read-more-button][How to add Read more button?]]
   - [[#how-to-use-htmlize-to-render-code-block][How to use htmlize to render code block]]
   - [[#how-to-install-my-emacs-theme][How to install my emacs theme]]

* Why fork ?

  Before I start to use [[https://github.com/CodeFalling/hexo-renderer-org][hexo-renderer-org]], I already have another tool called [[https://github.com/coldnew/org-hexo][org-hexo]], which can use org-mode's publish method to generate html code then let [[https://hexo.io][hexo]] renderer it. However, since my posts grow large, the org-publish is more slow then I think. That's why I try the [[https://github.com/CodeFalling/hexo-renderer-org][hexo-renderer-org]].

  The [[https://github.com/CodeFalling/hexo-renderer-org][hexo-renderer-org]] is really greate but it doesn't support use emacs's =htmlize= to render my code block, and that's why I create my fork.

  Some features may PR back to [[https://github.com/CodeFalling/hexo-renderer-org][CodeFalling/hexo-render-org]] if the original author accept that feature.

* Difference with original one

  The main difference is:

  - This fork use =emacs daemon= to speedup render speed.
  - This fork support use emacs's =htmlize= to syntax highlight your code block.

* Installation

  Switch to your blog directory and run:

  #+BEGIN_SRC sh
    npm install https://github.com/coldnew/hexo-renderer-org#coldnew --save
  #+END_SRC

  Then restart your hexo server.

* Options

  You can configure this plugin in ~_config.yml~.

  #+BEGIN_SRC yaml
      org:
        emacs: 'emacs'
        emacsclient: 'emacsclient'
        common: |
          ,#+OPTIONS: toc:nil
          ,#+BIND: org-html-postamble \"Last Updated %C.</br>Render by <a href='https://github.com/coldnew/hexo-renderer-org'>coldnew/hexo-renderer-org</a> with %c\"
        cachedir: './hexo-org-cache/'
        clean_cache: true
        theme: 'leuven'
        user_config: './emacs/init.el'
  #+END_SRC

  And here's some doc:

  | config      | description                             | default value                                              |
  |-------------+-----------------------------------------+------------------------------------------------------------|
  | emacs       | executable file of emacs                | emacs                                                      |
  | emacsclient | executable file of emacsclient          | emacsclient                                                |
  | common      | common org content you'll use           | #+OPTIONS: toc:nil num:nil\n#+BIND: org-html-postamble nil |
  | cachedir    | where cache file located                | ./hexo-org-cache/                                          |
  | clean_cache | set true to clean cache by 'hexo clean' | false                                                      |
  | theme       | emacs's theme you want to use           |                                                            |
  | user_config | extra emacs config you want to load     |                                                            |
  | debug       | Show more debug message                 | false                                                      |

* Create Post

  Create =source/_posts/foobar.org= with followin content:

  #+BEGIN_SRC org
    ,#+TITLE: Hello World
    ,#+DATE: <2017-03-05 Sun 08:52>
    ,#+LAYOUT: post
    ,#+CATEGORIES: orgmode
    ,#+TAGS: hexo, org-mode

    Welcome to [[https://github.com/coldnew/hexo-renderer-org][coldnew/hexo-renderer-org]]!

    ,#+HTML: <!-- more -->

    You also can add some code block:

    ,#+BEGIN_SRC js
      console.log("hi");
    ,#+END_SRC
  #+END_SRC
* Front-matters

  [[https://orgmode.org/][org-mode]] has it's own way to describe meta info:

  | Front-matter | org-mode     | value                                                      |
  |--------------+--------------+------------------------------------------------------------|
  | layout       | #+LAYOUT     | post/page                                                  |
  | title        | #+TITLE      | string                                                     |
  | date         | #+DATE       | <2017-04-15 Sat 12:30>, use ~M-x org-time-stamp~ to insert |
  | updated      | #+UPDATED    | <2017-04-15 Sat 12:30>, use ~M-x org-time-stamp~ to insert |
  | comments     | #+COMMENTS   | yes/no                                                     |
  | tags         | #+TAGS       | tag1, tag2, tag3                                           |
  | categories   | #+CATEGORIES | string                                                     |

  To insert date in org-mode, the default keybinding is =C-c .=, you can also use =C-u C-c .= instead.

* Tutorials

  For more tutorials, please see:

  - [[https://coldnew.github.io/hexo-org-example/2017/03/05/getting-started-with-hexo-and-org-mode/][Getting started with hexo and org-mode]]

* Q & A

** How to add Read more button?

   Place =#+HTML: <!-- more -->= in where you would like to add a ~Read more~.

** How to use htmlize to render code block

   config in your ~_config.yml~

   #+BEGIN_SRC yaml
     highlight:
       enable: false   # <--- Set this false to enable use emacs syntax highligt code block
   #+END_SRC

** How to install my emacs theme

   If the emacs theme you want to use is not installed by default, you can setup the ~_config.yml~

   For example, if we want to use [[https://github.com/kuanyui/moe-theme.el][moe-theme]] for our code block, we need to edit =_config.yml= like this:

   #+BEGIN_SRC yaml
       org:
         # skip ...
         theme: 'moe-dark'
         user_config: './emacs/init.el'
   #+END_SRC

   Then add following code to your =./emacs/init.el=.

   #+BEGIN_SRC emacs-lisp
     ;; install moe-theme
     (package-install 'moe-theme)
   #+END_SRC
